name: Emma Dickson
title: Emma Dickson
url: www.emmadickson.info
description: Emma Dickson is a Data Scientist/Software Developer who wants to work on challenging projects and conserve software based art.
author: Emma Dickson
image: images/me.jpg
social:
  name: Emma Dickson
  links:
    - https://www.linkedin.com/in/emma-dickson-86b1b499/
    - https://github.com/emmadickson

google_site_verification: UA-116279820-1
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
