
name: Emma Dickson
title: Emma Dickson
description: Emma Dickson's a Data Scientist/Engineer who wants to work on interesting projects and conserve digital art.
url: www.emmadickson.info
author: Emma Dickson
image: images/me.png
logo: images/header.png
email: emma.jk.dickson@gmail.com
twitter:
  username: emmamofodickson
  card: summary
github_username:  emmadickson

social:
  name: Emma Dickson
  links:
    - https://github.com/emmadickson
    - https://www.linkedin.com/in/emma-dickson-86b1b499/

markdown: kramdown

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
