name: Emma Dickson
title: Emma Dickson
url: https://emmadickson.info/
description: Emma Dickson is a Data Engineer, TBM Technician and Artist.
author: Emma Dickson
image: images/me.jpg
social:
  name: Emma Dickson
  links:
    - https://www.linkedin.com/in/emma-dickson-86b1b499/
    - https://github.com/emmadickson
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
