# Site settings
title: Emma Dickson
email: emma.jk.dickson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Emma Dickson's a Data Scientist/Software Developer who wants to work on interesting Data Science projects and conserve digital art
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.emmadickson.info" # the base hostname & protocol for your site
twitter_username: emmamofodickson
github_username:  emmadickson

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
